### ISSUE TITLE
Pharmaceutical Product Identifier (PHPID) Code System for vaccineCode

### ISSUE THREAD

**Issue by p9g** [HL7/fhir-shc-vaccination-ig#143]
IPS connectathon track kickoff on 12 May had a briefing on PHPID.  I asked about it on Zulip https://chat.fhir.org/#narrow/stream/207835-IPS/topic/PHPID 

If at some point PHPID is ready to use in a FHIR context, it should be added as an option for Immunization.vaccineCode.

**Comment by masnick** [comment]
We are now attempting to narrow the set of terminology used for `vaccineCode`.
