### ISSUE TITLE
Prototype assertion of past infection (recovery status)

### ISSUE THREAD

**Issue by nkarip** [HL7/fhir-shc-vaccination-ig#157]
Prototype use of a Condition profile to assert recovery from past infection, to align with upcoming international standards such as DGC. Use cases:
- allow people with persistent positive tests to "pass" based on recent infection status (as per DGC, "individuals who recover from COVID-19 can continue to test positive for SARS-CoV-2 for some time after no longer being infectious")
- evidence of natural immunity for people who require proof of vaccination but haven't been vaccinated yet because of recent infection or having received mAb

Providing a positive lab test alone to indicate recent infection may not be sufficient. Issuer may have diagnosed or managed COVID but not performed the positive test on site. Verifiers might also require an assertion of clinical infection in addition to a positive test to verify it was not a false positive.

**Comment by p9g** [comment]
Note DGC (Digital Green Certificate) has been renamed the EU Digital COVID Certificate (DCC).

**Comment by masnick** [comment]
Closing for now. Feel free to re-open.
