### ISSUE TITLE
Add method of specimen collection to lab profile

### ISSUE THREAD

**Issue by nkarip** [HL7/fhir-shc-vaccination-ig#165]
Request from some issuers/verifiers to document method of specimen collection in lab credentials, in case a verifier has requirements regarding collection. Options could include collected by a health professional, performed by patient under in-person observation, performed by patient under virtual / webcam observation, performed by patient without being observed.

**Comment by jmandel** [comment]
Quick note that "by patient" is a nice shorthand here, but the main categories described above would apply just as well when (say) a parent or caregiver is collecting a specimen from a patient (observed, virtually observed, not oobserved). We should make sure our definitions are clear on this point.

**Comment by masnick** [comment]
Agreed! I believe the codes we want are:

1. Collected by non-HCW, unobserved
2. Collected by non-HCW, virtually observed
3. Collected by non-HCW, observed in person
4. Collected by HCW

Am I missing any?

**Comment by masnick** [comment]
Also: how do we handle when the sample is collected by a HCW, but the HCW is not affiliated with the organization providing care. Example: I'm a nurse and collect the sample for my child. Do I count as a HCW?

**Comment by jmandel** [comment]
I think our guidance can leave this up to the issuer: they should populate "collected by HCW" if they have confidence that their own policies and practices were followed. (A nurse collecting samples for his own child generally wouldn't "count" from this perspective, because ... they wouldn't have a relationship with the performing lab; the lab can't have much confidence that their practices/policies are in play.)

**Comment by nkarip** [comment]
I did a LOINC and SNOMED search and did not find codes that really convey the options above, either single codes or even combinations that could be used together. There isn't a code that generically represents a patient-performed procedure such as sample collection, and did not find anything close to 'observed', 'supervised', 'monitored', etc. There are encounter status codes that sort-of represent in-person vs remote encounter, but that was the closest I could find.

Long way of saying we might be better off with an extension and a custom set of codes. What do we think about -
http://hl7.org/fhir/uv/smarthealthcards-vaccination/StructureDefinition/laboratory-sample-collection-method
lab-collect | individual-collect-unobserved | individual-collect-virtual-observed | individual-collect-in-person-observed

**Comment by jmandel** [comment]
I like those proposed codes!

Re: where they go.... why use an extension instead of using Observation.method for them? And just to stir the pot, we could also use a security tag for this, treating it similarly to how we represent IAL. (I think any of these would be fine, just want to make sure I understand the reasoning.)

**Comment by nkarip** [comment]
If we use CodeableConcept/Coding, we will have to define a system or submit a set of codes to some authority. With a code with-a-small-c we can get away without it. But we can go with Method if people prefer. Any suggestions for system?

I suspect the security tag will raise objections in balloting, it is a much looser interpretation of a security label than IAL. We would also have to have a system there, we already got pushback when we initially modeled IAL without a system. We could float that by the working groups and see though.

**Comment by jmandel** [comment]
I think whether we use a `CodeableConcept`, `Coding`, or a `code`, we'd need to define a CodeSystem of allowed values, and a ValueSet to bind the element to. (As an exampe: in the core FHIR spec, `Patient.gender` is a `code`, with a ValueSet (http://hl7.org/fhir/ValueSet/administrative-gender) and a CodeSystem (http://hl7.org/fhir/administrative-gender) defined to make it work.)

**Comment by grahamegrieve** [comment]
note that this isn't actually 'method of specimen collection' which is like spitting or scraping or swabbing. This is something different...

**Comment by jmandel** [comment]
The [documentation on Observation.method`](http://build.fhir.org/observation-definitions.html#Observation.method) states:

* (short): How it was done
* (long): Indicates the mechanism used to perform the observation

Might want to bring this back to HL7's Orders and Observations WG if

**Comment by masnick** [comment]
Closing as #191 covers this
