### ISSUE TITLE
Consider whether vaccination reaction profile should have a different parent

### ISSUE THREAD

**Issue by nkarip** [HL7/fhir-shc-vaccination-ig#166]
Based on discussion during previous IG public meeting, consider whether the experimental vaccine reaction profile should be a child of AllergyIntolerance of AdverseEvent rather than Observation.

Related proposal - https://confluence.hl7.org/display/FHIR/FHIR+Implementation+Guide+for+Transfusion+and+Vaccination+Adverse+Event+Reporting.

**Comment by masnick** [comment]
Look at #131 when doing this.

**Comment by masnick** [comment]
We removed this experimental profile from the IG, so closing this issue.
