### ISSUE TITLE
ATC code system URL should use http not https

### ISSUE THREAD

**Issue by p9g** [HL7/fhir-shc-vaccination-ig#169]
http://tx.fhir.org/r4/CodeSystem?_format=json&url=http://www.whocc.no/atc works but
http://tx.fhir.org/r4/CodeSystem?_format=json&url=https://www.whocc.no/atc does not work

See https://github.com/HL7/fhir-shc-vaccination-ig/blob/main/input/fsh/value_sets.fsh#L123

change system URL to not use http**s**; i.e., should be http://www.whocc.no/atc

Also note discussion at https://chat.fhir.org/#narrow/stream/179202-terminology/topic/atc.20or.20atc_ddd_index
i.e., THO needs fixing

**Comment by nkarip** [comment]
Made this change on the code-system-examples branch.
