### ISSUE TITLE
Links to LOINC lab results codes lead to a 404

### ISSUE THREAD

**Issue by p2-apple** [HL7/fhir-shc-vaccination-ig#170]
Clicking any of the LOINC links in the table under http://build.fhir.org/ig/dvci/vaccine-credential-ig/branches/main/ValueSet-qualitative-lab-result-findings.html#expansion leads to "Page Not Found".

**Comment by nkarip** [comment]
The expansion is generated by the FHIR IG publisher and not defined in this repo, so unfortunately we have no way of fixing these links.

**Comment by nkarip** [comment]
Publisher fixed links.
