### ISSUE TITLE
Update README.md link to IG

### ISSUE THREAD

**Issue by p9g** [HL7/fhir-shc-vaccination-ig#171]
https://github.com/HL7/fhir-shc-vaccination-ig/blob/main/README.md

CI build of this IG available at <http://build.fhir.org/ig/dvci/vaccine-credential-ig/branches/main/>.

should be changed to 

CI build of this IG available at <http://build.fhir.org/ig/HL7/fhir-shc-vaccination-ig/>.

**Comment by nkarip** [comment]
Fixed.
